# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-28 13:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='ddate',
            field=models.DateField(default=datetime.datetime(2018, 1, 28, 13, 45, 26, 91853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
