# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180128_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='ddate',
            field=models.DateField(),
        ),
    ]
