# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20180328_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('accept_nums', models.CharField(max_length=30)),
                ('submisions_nums', models.CharField(max_length=30)),
                ('context', models.CharField(max_length=10000)),
                ('Input', models.CharField(max_length=3000)),
                ('Output', models.CharField(max_length=3000)),
                ('sample_input', models.CharField(max_length=1000)),
                ('sample_output', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=255)),
                ('recommend', models.CharField(max_length=255)),
                ('lmit', models.CharField(max_length=255)),
            ],
        ),
    ]
