# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='lmit',
        ),
    ]
