# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20180502_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                #('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
            ],
        ),
    ]
